name: Run my Flask Application

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r req.txt

      - name: Run Flask application
        run: |
          . venv/bin/activate
          gunicorn -w 4 -b 0.0.0.0:8000 app:app

      - name: Run a script
        run: echo "Gunicorn is started and flask app is running at 0.0.0.0:8000" > /home/shankjbs571/message.txt
