name: Run my Flask Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.211.3.181 << 'EOF'
        "
        echo 'WE CAN LOGIN AND ggRUN THE SCRIPT' > /home/ubuntu/MessageFromActions.txt
        "

    # steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2

      # - name: Set up SSH and run a Script
      #   env:
      #     PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     HOST_NAME: ${{ secrets.HOST_IP_ADDR }}
      #     USER_NAME: ${{ secrets.USER_NAME }}

      #   run: | 
      #       echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #       ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 
            # "
            # echo 'WE CAN LOGIN AND ggRUN THE SCRIPT' > /home/ubuntu/MessageFromActions.txt
            # "
            

