name: CICD

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running on a self-hosted runner" > /home/shankjbs571/message.txt
